name: extract-k6

services:
  k6:
    image: grafana/k6:latest
    container_name: extract-k6-rust
    environment:
      BASE_URL: ${BASE_URL:-https://traefik}
      VHOST: ${VHOST:-extract-service.universidad.localhost}
      SPIKE_VUS: ${SPIKE_VUS:-25}
    volumes:
      - ./scripts:/scripts:ro
    networks:
      - mired

networks:
  mired:
    external: true